services:
  - type: web
    name: bookingreport-backend-web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 10000

  - type: worker
    name: bookingreport-backend-scheduler
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python scheduler.py
    envVars: []